name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build docker
        run: docker build -t test-${GITHUB_REF_NAME} -f Dockerfile .

      - name: Run tests
        run: docker run test-${GITHUB_REF_NAME} /entrypoint.sh

  release:
    needs: [ build ]
    # Run this job on git tag v1, v2, etc.
    if: startsWith(github.ref, 'refs/tags/v')
    name: release
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      # Unfortunately we can not share newly built docker images between jobs,
      # so we have to build (or pull) image again.
      - name: Build docker
        run: docker build -t test-${GITHUB_REF_NAME} -f Dockerfile .

      - name: Login to ECR
        run: 'aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 541575352130.dkr.ecr.eu-west-1.amazonaws.com'

      - name: Tag docker image
        run: 'docker tag test-${GITHUB_REF_NAME} 541575352130.dkr.ecr.eu-west-1.amazonaws.com/test:test-${GITHUB_REF_NAME}'

      - name: Push docker image
        run: 'docker push 541575352130.dkr.ecr.eu-west-1.amazonaws.com/test:test-${GITHUB_REF_NAME}'

