name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build docker
        run: docker build -t test-${GITHUB_REF##*/} -f Dockerfile .

      - name: Show docker images
        run: docker images

      - name: Run tests
        run: docker run test-${GITHUB_REF##*/} /entrypoint.sh

  release:
    needs: [ build ]
    if: startsWith(github.ref, 'refs/tags/v')
    name: release
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Show docker images
        run: docker images

      - name: Login to ECR
        run: 'aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 541575352130.dkr.ecr.eu-west-1.amazonaws.com'

      - name: Tag docker image
        run: 'docker tag test-${GITHUB_REF##*/} 541575352130.dkr.ecr.eu-west-1.amazonaws.com/test:test-${GITHUB_REF##*/}'

      - name: Push docker image
        run: 'docker push 541575352130.dkr.ecr.eu-west-1.amazonaws.com/test:test-${GITHUB_REF##*/}'

