name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build docker
        run: docker build -t test:${GITHUB_REF##*/} -f Dockerfile . 

      - name: Run tests
        run: docker run test:${GITHUB_REF##*/} /entrypoint.sh

